### ISSUE TITLE
When the sprite toughes the bottom of the screen it gets stuck and cant move back up

### ISSUE THREAD

**Issue by Fishlips525** [WSNCoding/Trump-Shooter#3]
This should be quite easy to fix but I don't have the time as I'm going away tomorrow :smiley: 

This is for SUPER#RENDERWASG btw
I think the bit that bugs it is on lines 70 and 73 with the syntax which bugs it

Loving these emojis btw :smiley_cat: :smiley:

**Comment by Fishlips525** [comment]
Does everyone know how to do the emojis, if you don't just make a colon and there's a kind of drop-down menu with the options

**Comment by TheMiner63** [comment]
Um what's happening with trump shooter I haven't looked at all... Is there new code for physics or game logic?

**Comment by Fishlips525** [comment]
IDK leo added a tonne of random stuff

**Comment by Fishlips525** [comment]
We definitely need to structure the files better, its really hard to find certain files

**Comment by Fishlips525** [comment]
Leo you can fix this

**Comment by TheMiner63** [comment]
We Sade we wouldn't do it object oriented totally Leo isn't listening

**Comment by NinjutsuFish** [comment]
Done it just haven't uploaded the file soz
Working on shooting
This should be quite easy to fix but I don't have the time as I'm going away tomorrow :smiley:

Loving these emojis btw

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/WSNCoding/Trump-Shooter/issues/3
